Feature add optimism goerli network
Giveth/impact-graph pull request #1039
Opened 2023-06-21 22:29 UTC by CarlosQ96

2023-06-25 06:20 UTC, mohammadranjbarz commented on migration/1687383705794-AddOptimismGoerliTokens.ts
> +    );
I think you need to add a condition to not add these test tokens in production env

2023-06-25 06:21 UTC, mohammadranjbarz requested changes
Thanks @CarlosQ96 , except comment that I put in migrations file other things seems good to me

2023-06-25 18:08 UTC, CarlosQ96 commented
Thanks Mohammad addded the condition to not add them in production

2023-06-26 05:30 UTC, mohammadranjbarz approved these changes
Thanks @CarlosQ96  LGTM

2023-06-26 05:30 UTC, merged