Dont return tokens that doesnt have corresponding recipient address in getProjectAcceptTokens
Giveth/impact-graph pull request #1235
Opened 2024-01-07 13:17 UTC by mohammadranjbarz

@aminlatifi  It's what @alireza-sharifpour  suggested here

related to https://github.com/Giveth/giveth-dapps-v2/issues/3543#issuecomment-1880024305

2024-01-07 15:02 UTC, aminlatifi requested changes
@mohammadranjbarz @alireza-sharifpour I pushed a commit to fix the related issue which happened on the frontend though. It must work as it used to before.

2024-01-07 15:02 UTC, aminlatifi commented on src/resolvers/projectResolver.test.ts
> +
Let's add a few more tests to be sure it will work for solana as well, and a combination of networks.

2024-01-07 15:02 UTC, aminlatifi commented on src/resolvers/projectResolver.ts
> +          'tokens.networkId IS NOT NULL',
Why do we need this condition?

2024-01-07 16:48 UTC, MoeNick commented
If you create issues regarding the Epic pls attach it to the Epic or related user story as well

2024-01-08 08:15 UTC, aminlatifi commented
https://github.com/Giveth/impact-graph/issues/1172

2024-01-14 13:48 UTC, aminlatifi commented
@mohammadranjbarz Please resolve conflicts

2024-01-14 15:35 UTC, MoeNick commented
shall I move it to QA?

2024-01-15 07:33 UTC, aminlatifi commented
@mohammadranjbarz Please resolve conflicts

2024-01-15 07:34 UTC, aminlatifi commented
@MoeNick It's not merged yet

2024-01-15 08:05 UTC, mohammadranjbarz commented
> @mohammadranjbarz Please resolve conflicts

Done.

2024-01-15 08:31 UTC, aminlatifi commented
@mohammadranjbarz @alireza-sharifpour If you agree let's postpone merging this change as the FE is adopted to the old API result. Changing this at this point may cause issues at this moment that we have to ship Solana and improve dapp reliability.

2024-01-29 07:41 UTC, merged