start the import of tokens lost (wip)
Giveth/impact-graph pull request #1236
Opened 2024-01-10 06:08 UTC by CarlosQ96

2024-01-11 22:44 UTC, CarlosQ96 commented
Will not import multisig donations, those were not part of the round and we just released that. There should not be any or any communication about it. Not sure how they were done.

2024-01-12 15:52 UTC, mateodaza approved these changes

2024-01-12 15:52 UTC, mateodaza commented on src/services/cronJobs/importLostDonationsJob.ts
> +    to: transactionTo as string,
Awesome job man. @CarlosQ96 
Just make sure you're checking the from and to values on the Transfer event from the logs instead. Then you're making sure you're grabbing the right values each time. Check the multisig code for it, we did something similar

2024-01-14 05:14 UTC, CarlosQ96 commented on src/services/cronJobs/importLostDonationsJob.ts
> +    to: transactionTo as string,
Thanks man

2024-01-14 05:40 UTC, CarlosQ96 commented
@aminlatifi @mohammadranjbarz can review please so we import the donations. Ill handle the optimism ones first then the rest. This should work for all.

2024-01-14 08:34 UTC, mohammadranjbarz commented
> @aminlatifi @mohammadranjbarz can review please so we import the donations. Ill handle the optimism ones first then the rest. This should work for all.
@CarlosQ96 
Name PR should not be 
**Import lost donations into DB cronjob** ?

2024-01-14 08:35 UTC, mohammadranjbarz requested changes

2024-01-14 08:35 UTC, mohammadranjbarz commented on src/services/cronJobs/importLostDonationsJob.ts
> +        qfRoundId: qfRound?.id,
@CarlosQ96  Should not add qfRound to all missed donations, we should check if project is connected to qfRound, then add `qfRoundId` to donation ( and its nice to have a test case for that scenario as well)

2024-01-15 14:04 UTC, mohammadranjbarz commented on src/services/cronJobs/importLostDonationsJob.ts
> +        qfRoundId: qfRound?.id,
I did it myself just please take a look yourself too

2024-01-15 15:30 UTC, mohammadranjbarz approved these changes
Thanks @CarlosQ96 
I skipped the changes for qfRound as it's just for our tx hashes

2024-01-15 15:30 UTC, merged