Fill solana network ids with correct value
Giveth/impact-graph pull request #1245
Opened 2024-01-15 13:36 UTC by mohammadranjbarz

related to #1244

2024-01-16 12:06 UTC, mohammadranjbarz commented
@aminlatifi  Now I fill the `networkId` in backend forthese web services:
* createDonation
* updateProject
* createProject
* updateProjectVerificationForm

Also we had two migration files for solana I checked the production and saw just one of them has been executed so I edited the second one for adding spl tokens in db

2024-01-16 13:00 UTC, aminlatifi requested changes

2024-01-16 13:00 UTC, aminlatifi commented on migration/data/seedTokens.ts
> +    networkId: NETWORK_IDS.SOLANA_DEVNET,
```suggestion
    networkId: NETWORK_IDS.SOLANA_TESTNET,
```

2024-01-16 13:00 UTC, aminlatifi commented on src/repositories/projectRepository.ts
> +          : relatedAddress.networkId,
If it was me, I would move this logic to a method as it is repeated plenty of times.

2024-01-17 08:05 UTC, aminlatifi approved these changes

2024-01-17 08:06 UTC, mohammadranjbarz commented on src/repositories/projectRepository.ts
> +          : relatedAddress.networkId,
You are right, done.

2024-01-17 08:06 UTC, mohammadranjbarz commented on migration/data/seedTokens.ts
> +    networkId: NETWORK_IDS.SOLANA_DEVNET,
Done

2024-01-17 08:06 UTC, aminlatifi commented
@mohammadranjbarz Please be sure the vault is filled with appropriate values (staging + production) and merge.

2024-01-17 08:09 UTC, mohammadranjbarz commented
> @mohammadranjbarz Please be sure the vault is filled with appropriate values (staging + production) and merge.

@aminlatifi Thanks for reminding, done

2024-01-17 08:10 UTC, merged