add segment call for project unlisted
Giveth/impact-graph pull request #131
Opened 2021-09-16 23:54 UTC by divine-comedian

2021-09-19 17:44 UTC, mohammadranjbarz commented on resolvers/projectResolver.ts
> +      const user = await User.find({ id: Number(project.admin) })
You can use `User.findOne` instead of `User.find` and it will return one object so you don't have to use `user[0]` you can simply use `user`

2021-09-19 17:44 UTC, mohammadranjbarz commented on resolvers/projectResolver.ts
> +          null
You can use  `user?.segmentUserId()` instead of null, I saw it used like this in another parts of codes

2021-09-19 17:44 UTC, mohammadranjbarz commented on resolvers/projectResolver.ts
> +    const segmentProject = await projects.map( async project => {
You don't use `segmentProject` so you can just call `await projects.map...` without  putting the result in the `segmentProject`, simply you can remove `const segmentProject = ` from this line

2021-09-19 17:53 UTC, mohammadranjbarz requested changes
Please change the requested changes, other thins is good to me

2021-09-19 21:43 UTC, divine-comedian commented
@mohammadranjbarz  I incorporated the changes you suggested and now the code is throwing compilation errors! 

```
  await projects.map( async project => {
      const projectOwner = await User.findOne({ id: Number(project.admin) })
      console.log(projectOwner)
      if (project.listed === false) {

        analytics.track(
          'Project unlisted',
          `givethId-${project.admin}`,
          {
            id: project.id,
            email: projectOwner.email,
            title: project.title,
            LastName: projectOwner.lastName,
            FirstName: projectOwner.firstName,
            OwnerId: project.admin,
            slug: project.slug,
            listed,
          },
          projectOwner?.segmentUserId()
        )
      }
    })
    
```

```
    [ERROR] 14:38:26 ⨯ Unable to compile TypeScript:
resolvers/projectResolver.ts:1045:20 - error TS2532: Object is possibly 'undefined'.

1045             email: projectOwner.email,
                        ~~~~~~~~~~~~
resolvers/projectResolver.ts:1047:23 - error TS2532: Object is possibly 'undefined'.

1047             LastName: projectOwner.lastName,
                           ~~~~~~~~~~~~
resolvers/projectResolver.ts:1048:24 - error TS2532: Object is possibly 'undefined'.

1048             FirstName: projectOwner.firstName,
                            ~~~~~~~~~~~~
Error: ⨯ Unable to compile TypeScript:
resolvers/projectResolver.ts:1045:20 - error TS2532: Object is possibly 'undefined'.

1045             email: projectOwner.email,
                        ~~~~~~~~~~~~
resolvers/projectResolver.ts:1047:23 - error TS2532: Object is possibly 'undefined'.

1047             LastName: projectOwner.lastName,
                           ~~~~~~~~~~~~
resolvers/projectResolver.ts:1048:24 - error TS2532: Object is possibly 'undefined'.

1048             FirstName: projectOwner.firstName,
                            ~~~~~~~~~~~~
```

the console.log properly logs all of the properties from projectOwner but when we try to map them in the analytics the nested values can't be found!

2021-09-20 04:03 UTC, mohammadranjbarz commented
> projectOwner.email

Sorry, you should change `projectOwner.email` to `projectOwner?.email` . the `?.` make sure that if `projectOwner` is undefined/null you would not get null point exception
so you should do that for the rest of usage as well :
 `projectOwner.title` ---> `projectOwner?.title`
 `projectOwner.firstName` ---> `projectOwner?.firstName`
 `projectOwner.lastName` ---> `projectOwner?.lastName`

2021-09-20 04:04 UTC, mohammadranjbarz commented
> @mohammadranjbarz I incorporated the changes you suggested and now the code is throwing compilation errors!
> 
> ```
>   await projects.map( async project => {
>       const projectOwner = await User.findOne({ id: Number(project.admin) })
>       console.log(projectOwner)
>       if (project.listed === false) {
> 
>         analytics.track(
>           'Project unlisted',
>           `givethId-${project.admin}`,
>           {
>             id: project.id,
>             email: projectOwner.email,
>             title: project.title,
>             LastName: projectOwner.lastName,
>             FirstName: projectOwner.firstName,
>             OwnerId: project.admin,
>             slug: project.slug,
>             listed,
>           },
>           projectOwner?.segmentUserId()
>         )
>       }
>     })
>     
> ```
> 
> ```
>     [ERROR] 14:38:26 ⨯ Unable to compile TypeScript:
> resolvers/projectResolver.ts:1045:20 - error TS2532: Object is possibly 'undefined'.
> 
> 1045             email: projectOwner.email,
>                         ~~~~~~~~~~~~
> resolvers/projectResolver.ts:1047:23 - error TS2532: Object is possibly 'undefined'.
> 
> 1047             LastName: projectOwner.lastName,
>                            ~~~~~~~~~~~~
> resolvers/projectResolver.ts:1048:24 - error TS2532: Object is possibly 'undefined'.
> 
> 1048             FirstName: projectOwner.firstName,
>                             ~~~~~~~~~~~~
> Error: ⨯ Unable to compile TypeScript:
> resolvers/projectResolver.ts:1045:20 - error TS2532: Object is possibly 'undefined'.
> 
> 1045             email: projectOwner.email,
>                         ~~~~~~~~~~~~
> resolvers/projectResolver.ts:1047:23 - error TS2532: Object is possibly 'undefined'.
> 
> 1047             LastName: projectOwner.lastName,
>                            ~~~~~~~~~~~~
> resolvers/projectResolver.ts:1048:24 - error TS2532: Object is possibly 'undefined'.
> 
> 1048             FirstName: projectOwner.firstName,
>                             ~~~~~~~~~~~~
> ```
> 
> the console.log properly logs all of the properties from projectOwner but when we try to map them in the analytics the nested values can't be found!

@divine-comedian 
You should change `projectOwner.email` to `projectOwner?.email` . the `?.` make sure that if `projectOwner` is undefined/null you would not get null point exception
so you should do that for the rest of usage as well :
 `projectOwner.title` ---> `projectOwner?.title`
 `projectOwner.firstName` ---> `projectOwner?.firstName`
 `projectOwner.lastName` ---> `projectOwner?.lastName`

2021-09-20 16:57 UTC, divine-comedian commented
@mohammadranjbarz changes are in! I added a new commit, its working fine local now and ready for review and merge

2021-09-20 17:13 UTC, mohammadranjbarz approved these changes
@divine-comedian Thanks Man

2021-09-20 17:13 UTC, merged