Feat/arbitrum
Giveth/impact-graph pull request #1341
Opened 2024-02-19 06:31 UTC by aminlatifi

2024-02-19 17:44 UTC, CarlosQ96 approved these changes
LGTM Amin thanks!

2024-02-20 08:06 UTC, mohammadranjbarz requested changes
Thanks @aminlatifi 
It seems good to me, but there are some things that should add Arbitrum networkId there:
1. `qfRoundTab.ts`
2. `tokenTab.ts`

2024-02-20 08:06 UTC, mohammadranjbarz commented on src/services/chains/index.test.ts
> +  it('should return transaction detail for normal transfer on CELO Alfajores', async () => {
@aminlatifi  Please change the description from Celo to Arbitrum

2024-02-20 09:04 UTC, aminlatifi commented
> Thanks @aminlatifi It seems good to me, but there are some things that should add Arbitrum networkId there:
> 
> 1. `qfRoundTab.ts`
> 2. `tokenTab.ts`

I had added already at some points, which part do you mean?

2024-02-20 09:06 UTC, jainkrati approved these changes

2024-02-20 10:20 UTC, merged