Feature/The Giving Blocks
Giveth/impact-graph pull request #234
Opened 2021-12-06 06:37 UTC by CarlosQ96

Issue: #160 
First version, gotta refactor a bit.

Current Issues:
Api seem to break on multiple calls, but the docs don't specify api limit.
Our title validation seem to conflict.

Docs: https://the-giving-block.gitbook.io/public-api-documentation/

2021-12-07 12:20 UTC, mohammadranjbarz commented
Thanks @CarlosQ96 Its seems great, but I had some change requests that I made in https://github.com/Giveth/impact-graph/pull/236, please review and merge that

2021-12-09 12:43 UTC, mohammadranjbarz requested changes
Thanks @CarlosQ96 
Please applly changes requested, I would test the functionality later

2021-12-09 12:43 UTC, mohammadranjbarz commented on services/the-giving-blocks/api.ts
> +) => {
Could you please specify output type for this function?

2021-12-09 12:43 UTC, mohammadranjbarz commented on services/the-giving-blocks/syncProjectsCronJob.ts
> +const findOrCreateGivingBlocksCategory = async () => {
@CarlosQ96  please specify output type for this function

2021-12-09 12:43 UTC, mohammadranjbarz commented on services/the-giving-blocks/syncProjectsCronJob.ts
> +const getQualityScore = (description, hasImageUpload) => {
@CarlosQ96  please specify output type for this function

2021-12-09 12:43 UTC, mohammadranjbarz commented on services/the-giving-blocks/syncProjectsCronJob.ts
> +const getAppropriateSlug = async (slugBase: string) => {
@CarlosQ96  please specify output type for this function
PS: We used that before, that time we didn't write type, but it's good to write types from now on

2021-12-10 04:53 UTC, CarlosQ96 commented
@mohammadranjbarz made the changes. Ready to be merged!

2021-12-10 10:53 UTC, mohammadranjbarz approved these changes
Amazing work @CarlosQ96 
I have tested it and the functionality was ok

2021-12-10 10:53 UTC, merged