F 380 organization token integration
Giveth/impact-graph pull request #395
Opened 2022-03-03 12:07 UTC by mohammadranjbarz

related to #380

2022-03-13 07:31 UTC, mohammadranjbarz commented
@aminlatifi  The are many changes, so if you need a call to explain you what I did, please tell me

2022-03-14 14:00 UTC, aminlatifi requested changes

2022-03-14 14:00 UTC, aminlatifi commented on migration/1646305490859-seedOrganizations.ts
> +         ('giveth','Giveth','https://giveth.io'),
Let's use enum in src/entities/organization.ts for label

2022-03-14 14:00 UTC, aminlatifi commented on src/resolvers/projectResolver.ts
> +        .getOne();
Let's implement all in a single pure Query Builder query.

2022-03-14 14:00 UTC, aminlatifi commented on src/services/donationService.ts
> +    return organizationToken.length > 0;
Let's improve it. Just use queryBuilder and count instead of finding the entity

2022-03-14 14:00 UTC, aminlatifi commented on src/utils/tokenUtils.ts
> +  logger.info('findTokenByNetworkAndAddress', { address, networkId });
Let's remove it if it's not a convention

2022-03-14 14:00 UTC, aminlatifi commented on migration/1646303882607-seedTokes.ts
> +         ('Curve DAO Token','CRV','0x1337BedC9D22ecbe766dF105c9623922A27963EC',18, 100),
We should revise our approach in inserting tokens. Consider this case, the address has upper case and lower case characters. But in finding tokens we have assumed all characters are lowercase.

2022-03-15 18:08 UTC, merged