F 328 write test for donations from wallets
Giveth/impact-graph pull request #454
Opened 2022-04-02 10:30 UTC by FatemeGhasemi

Add test for  donationsFromWallets

Related to #328

2022-04-02 10:47 UTC, FatemeGhasemi commented
@mohammadranjbarz can you review this?

2022-04-03 18:16 UTC, mohammadranjbarz requested changes
@FatemeGhasemi Thanks, everything looks good, and tests passed, so just remove the  unused logs, then we can merge it

2022-04-03 18:16 UTC, mohammadranjbarz commented on src/resolvers/donationResolver.ts
> +    );
@FatemeGhasemi  Please remove unused logs

2022-04-04 04:51 UTC, mohammadranjbarz commented
@FatemeGhasemi Please resolve conflicts

2022-04-05 13:35 UTC, mohammadranjbarz approved these changes
Thanks, LGTM

2022-04-05 13:35 UTC, merged